services:
  mysqldb:
    container_name: mysql
    image: mysql:8
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: [ 'CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent' ]
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backnet
    # 可公開放env_file， 需加密的 使用secrets管理，再從environment引入
    env_file:
      - db/.env
    environment:
       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password

    expose:
      - '3306'
  redis:
    container_name: redis
    image: redislabs/redismod
    ports:
      - '6379:6379'
  web:
    container_name: web
    build:
      context: venv
      target: builder

    ports:
      - '8080:8080'
    networks:
      - backnet
    env_file:
      - venv/app/.env
    depends_on:
      mysqldb:
        condition: service_healthy
      redis:

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
networks:
  backnet:
